model-parameters:
  embedding-dim: 128
  units: 128
  layer-type: "blstm"
  n-layers: 1
  attention-type: "luong"

experiment-parameters:
  root-path: "results"
  optimizer: "adam"
  model-type: "rnn-based"