model-parameters:
  n-layers: 1
  d-model: 64
  dff: 64
  dropout: 0.1
  n-heads: 2
  input-pos-encoding: 1000
  target-pos-encoding: 1000

experiment-parameters:
  root-path: "results"
  model-type: "transformer"
  