model-parameters:
  n-layers: 1
  d-model: 128
  dff: 128
  dropout: 0.2
  n-heads: 4
  input-pos-encoding: 1000
  target-pos-encoding: 1000

experiment-parameters:
  root-path: "results"
  model-type: "transformer"
  