model-parameters:
  n-layers: 
    - 1
    - 2
  d-model:
    - 512
    - 256
    - 128
    - 64
  dff: 
    - 512
    - 256
    - 128
    - 64
  dropout: 
    - 0.2
    - 0.1
    - 0.0
  n-heads: 
    - 4
    - 2
  input-pos-encoding: 
    - 1000
  target-pos-encoding: 
    - 1000

experiment-parameters:
  root-path: "results"
  model-type: "transformer"
  